\version "2.24.0"

% Enable Sagittal accidentals with Ekmelily by passing --use_ekmelily.


\language "nederlands"

\header {
  title = "One-footed-bride tuning"
        subtitle = "BWV261 - last 4 measures in 17 limit"
    tagline = "Generated by features_to_lilypond.py coded by GitHub Copilot with assistance from Prent"
}

\paper {
  indent = 0
}

sagittalLegend = \markup \column {
  \vspace #1
  \line { \bold "Sagittal Legend (used in this score)" }
  \line { \override #'(font-name . "Bravura Text") \fontsize #9 \char ##xE301 " = -8.100c kleisma" }
  \line { \override #'(font-name . "Bravura Text") \fontsize #9 \char ##xE300 " = +8.100c kleisma" }
  \line { \override #'(font-name . "Bravura Text") \fontsize #9 \char ##xE303 " = -22.000c comma" }
  \line { \override #'(font-name . "Bravura Text") \fontsize #9 \char ##xE302 " = +22.000c comma" }
  \line { \override #'(font-name . "Bravura Text") \fontsize #9 \char ##xE305 " = -27.264c" }
  \line { \override #'(font-name . "Bravura Text") \fontsize #9 \char ##xE304 " = +27.264c" }
  \line { \override #'(font-name . "Bravura Text") \fontsize #9 \char ##xE309 " = -48.770c medium diesis" }
  \line { \override #'(font-name . "Bravura Text") \fontsize #9 \char ##xE308 " = +48.770c medium diesis" }
}

sopMusic = { \time 4/4 \numericTimeSignature
    \key b \minor
    a'4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE304 #}))
  b'!4
  cis''4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  d''!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  e''!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  fis''!2^\markup \tiny \italic "-10.00c"
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  e''!2
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  d''!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  cis''!4.
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  cis''!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  b'!4~
  b'4
  \bar "|."
}
altoMusic = { \time 4/4 \numericTimeSignature
    \key b \minor
    \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE303 #}))
  fis'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE304 #}))
  e'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE305 #}))
  e'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  d'!4^\markup \tiny \italic "+10.00c"
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  d''!8^\markup \tiny \italic "+10.00c"
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  cis''!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  b'!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE308 #}))
  ais'!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  b'!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE304 #}))
  cis''!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  ais'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE303 #}))
  b'!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  a'!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  g'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  fis'!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE303 #}))
  e'!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  dis'!4~
  dis'4
  \bar "|."
}
tenorMusic = { \time 4/4 \numericTimeSignature
    \key b \minor
    \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  d'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE302 #}))
  gis!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  ais!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  b!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE309 #}))
  cis'!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE302 #}))
  d'!2^\markup \tiny \italic "-10.00c"
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE304 #}))
  cis'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE304 #}))
  cis'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE303 #}))
  b!2
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  ais!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  b!4~
  b4
  \bar "|."
}
bassMusic = { \time 4/4 \numericTimeSignature
    \key b \minor
    \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  d!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  d'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  cis'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  b!4^\markup \tiny \italic "+10.00c"~
  b8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE302 #}))
  a!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE302 #}))
  g!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  fis!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  g!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  e!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE304 #}))
  fis!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  g!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE303 #}))
  fis!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE303 #}))
  e!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  fis!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  b,!4~
  b,4
  \bar "|."
}

\score {
    \new ChoirStaff <<
        \new Staff = "soprano" \with { instrumentName = "S" } { \clef treble \sopMusic }
        \new Staff = "alto"    \with { instrumentName = "A" } { \clef treble \altoMusic }
        \new Staff = "tenor"   \with { instrumentName = "T" } { \clef "treble_8" \tenorMusic }
        \new Staff = "bass"    \with { instrumentName = "B" } { \clef bass \bassMusic }
    >>
    \layout {
        \context {
            \ChoirStaff
            \consists "Span_bar_engraver"
        }
  }
}

\sagittalLegend
