\version "2.24.0"

% Enable Sagittal accidentals with Ekmelily by passing --use_ekmelily.


\language "nederlands"

\header {
  title = "Werckmeister-III Tuning"
        subtitle = "BWV261 - last 4 measures"
    tagline = "Generated by features_to_lilypond.py coded by GitHub Copilot with assistance from Prent"
}

\paper {
  indent = 0
}

sagittalLegend = \markup \column {
  \vspace #1
  \line { \bold "Sagittal Legend (used in this score)" }
  \line { \override #'(font-name . "Bravura Text") \fontsize #9 \char ##xE301 " = -8.100c kleisma" }
  \line { \override #'(font-name . "Bravura Text") \fontsize #9 \char ##xE300 " = +8.100c kleisma" }
}

sopMusic = { \time 4/4 \numericTimeSignature
    \key b \minor
    a'4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  b'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  cis''!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  d''!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  e''!8
  fis''2
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  e''!2
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  d''!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  cis''!2
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  b'!4~
  b'4
  \bar "|."
}
altoMusic = { \time 4/4 \numericTimeSignature
    \key b \minor
    fis'4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  e'!2
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  d'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  d''!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  cis''!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  b'!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  ais'!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  b'!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  cis''!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  ais'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  b'!8
  a'8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  g'!4
  fis'8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  e'!8
  dis'4~
  dis'4
  \bar "|."
}
tenorMusic = { \time 4/4 \numericTimeSignature
    \key b \minor
    \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  d'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  gis!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  ais!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  b!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  cis'!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  d'!2
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  cis'!2
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  b!2
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  ais!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  b!4~
  b4
  \bar "|."
}
bassMusic = { \time 4/4 \numericTimeSignature
    \key b \minor
    \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  d!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  d'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  cis'!4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  b!4~
  b8
  a8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  g!8
  fis8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  g!8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  e!8
  fis4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE300 #}))
  g!8
  fis8
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  e!4
  fis4
  \once \override Accidental.stencil = #(lambda (grob) (grob-interpret-markup grob #{ \markup \translate #'(0 . -2.0) \override #'(font-name . "Bravura Text") \fontsize #10 \char ##xE301 #}))
  b,!4~
  b,4
  \bar "|."
}

\score {
    \new ChoirStaff <<
        \new Staff = "soprano" \with { instrumentName = "S" } { \clef treble \sopMusic }
        \new Staff = "alto"    \with { instrumentName = "A" } { \clef treble \altoMusic }
        \new Staff = "tenor"   \with { instrumentName = "T" } { \clef "treble_8" \tenorMusic }
        \new Staff = "bass"    \with { instrumentName = "B" } { \clef bass \bassMusic }
    >>
    \layout {
        \context {
            \ChoirStaff
            \consists "Span_bar_engraver"
        }
  }
}

\sagittalLegend
