\version "2.24.0"

% Enable Sagittal accidentals with Ekmelily by passing --use_ekmelily.


\language "nederlands"

\header {
  title = "12 Tone Equal Tuning"
        subtitle = "BWV261 - last 4 measures"
    tagline = "Generated by features_to_lilypond.py coded by GitHub Copilot with assistance from Prent"
}

\paper {
  indent = 0
}



sopMusic = { \time 4/4 \numericTimeSignature
    \key b \minor
    a'4
  b'4
  cis''4
  d''8
  e''8
  fis''2
  e''2
  d''4
  cis''2
  b'4~
  b'4
  \bar "|."
}
altoMusic = { \time 4/4 \numericTimeSignature
    \key b \minor
    fis'4
  e'2
  d'4
  d''8
  cis''8
  b'8
  ais'8
  b'8
  cis''8
  ais'4
  b'8
  a'8
  g'4
  fis'8
  e'8
  dis'4~
  dis'4
  \bar "|."
}
tenorMusic = { \time 4/4 \numericTimeSignature
    \key b \minor
    d'4
  gis4
  ais4
  b8
  cis'8
  d'2
  cis'2
  b2
  ais4
  b4~
  b4
  \bar "|."
}
bassMusic = { \time 4/4 \numericTimeSignature
    \key b \minor
    d4
  d'4
  cis'4
  b4~
  b8
  a8
  g8
  fis8
  g8
  e8
  fis4
  g8
  fis8
  e4
  fis4
  b,4~
  b,4
  \bar "|."
}

\score {
    \new ChoirStaff <<
        \new Staff = "soprano" \with { instrumentName = "S" } { \clef treble \sopMusic }
        \new Staff = "alto"    \with { instrumentName = "A" } { \clef treble \altoMusic }
        \new Staff = "tenor"   \with { instrumentName = "T" } { \clef "treble_8" \tenorMusic }
        \new Staff = "bass"    \with { instrumentName = "B" } { \clef bass \bassMusic }
    >>
    \layout {
        \context {
            \ChoirStaff
            \consists "Span_bar_engraver"
        }
  }
}


