\version "2.24.0"

\header {
  title = "Sagittal Glyph Reference"
    subtitle = "Sagittal codepoint chart"
  tagline = "Generated by generate_sagittal_codepoint_chart.py"
}

\paper {
  indent = 0
}

\markup \column {
      \line { \typewriter "U+E300" \hspace #2 \typewriter "58112" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE300 }
      \line { \typewriter "U+E301" \hspace #2 \typewriter "58113" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE301 }
      \line { \typewriter "U+E302" \hspace #2 \typewriter "58114" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE302 }
      \line { \typewriter "U+E303" \hspace #2 \typewriter "58115" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE303 }
      \line { \typewriter "U+E304" \hspace #2 \typewriter "58116" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE304 }
      \line { \typewriter "U+E305" \hspace #2 \typewriter "58117" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE305 }
      \line { \typewriter "U+E306" \hspace #2 \typewriter "58118" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE306 }
      \line { \typewriter "U+E307" \hspace #2 \typewriter "58119" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE307 }
      \line { \typewriter "U+E308" \hspace #2 \typewriter "58120" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE308 }
      \line { \typewriter "U+E309" \hspace #2 \typewriter "58121" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE309 }
      \line { \typewriter "U+E30A" \hspace #2 \typewriter "58122" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE30A }
      \line { \typewriter "U+E30B" \hspace #2 \typewriter "58123" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE30B }
      \line { \typewriter "U+E30C" \hspace #2 \typewriter "58124" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE30C }
      \line { \typewriter "U+E30D" \hspace #2 \typewriter "58125" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE30D }
      \line { \typewriter "U+E30E" \hspace #2 \typewriter "58126" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE30E }
      \line { \typewriter "U+E30F" \hspace #2 \typewriter "58127" \hspace #2 \override #'(font-name . "Bravura Text") \fontsize #3 \char ##xE30F }
}
