#!/usr/bin/env python3
"""Generate a LilyPond chart of Sagittal font codepoints.

This helps verify which Unicode private-use codepoints map to which glyphs
for the installed Sagittal font.
"""

from __future__ import annotations

import argparse
from pathlib import Path


DEFAULT_FONT_CANDIDATES = [
    "Bravura Text",
    "Bravura",
    "Sagittal",
    "Sagittal Regular",
    "SagittalMusic",
    "Sagittal-Music",
    "Sagittal SMuFL",
]


def parse_hex_codepoint(value: str) -> int:
    value = value.strip().lower().replace("0x", "")
    return int(value, 16)


def lily_char_row(cp: int, font_name: str, size: int) -> str:
    hex_code = f"{cp:04X}"
    dec_code = str(cp)
    # Show hex and decimal labels plus rendered glyph from selected font.
    return (
        "\\line { "
        f'\\typewriter "U+{hex_code}" '
        f'\\hspace #2 \\typewriter "{dec_code}" '
        f'\\hspace #2 \\override #\'(font-name . "{font_name}") '
        f'\\fontsize #{size} \\char ##x{hex_code} '
        "}"
    )


def lily_char_row_multi(cp: int, font_names: list[str], size: int) -> str:
    hex_code = f"{cp:04X}"
    dec_code = str(cp)
    cols = [
        "\\line {",
        f'\\typewriter "U+{hex_code}"',
        f'\\hspace #2 \\typewriter "{dec_code}"',
    ]
    for name in font_names:
        cols.append(
            f'\\hspace #2 \\typewriter "{name}:" \\hspace #0.5 '
            f'\\override #\'(font-name . "{name}") \\fontsize #{size} \\char ##x{hex_code}'
        )
    cols.append("}")
    return " ".join(cols)


def build_lilypond(
    cp_start: int,
    cp_end: int,
    font_name: str,
    size: int,
    title: str,
    font_candidates: list[str] | None = None,
) -> str:
    if cp_end < cp_start:
        raise ValueError("end codepoint must be >= start codepoint")

    if font_candidates:
        rows = [lily_char_row_multi(cp, font_candidates, size) for cp in range(cp_start, cp_end + 1)]
        subtitle = "Sagittal codepoint chart (multi-font diagnostics)"
    else:
        rows = [lily_char_row(cp, font_name, size) for cp in range(cp_start, cp_end + 1)]
        subtitle = "Sagittal codepoint chart"
    body = "\n      ".join(rows)

    return f'''\\version "2.24.0"

\\header {{
  title = "{title}"
    subtitle = "{subtitle}"
  tagline = "Generated by generate_sagittal_codepoint_chart.py"
}}

\\paper {{
  indent = 0
}}

\\markup \\column {{
      {body}
}}
'''


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate LilyPond Sagittal codepoint chart")
    parser.add_argument("--output", required=True, help="Output .ly file")
    parser.add_argument("--start", default="E300", help="Start codepoint hex (default E300)")
    parser.add_argument("--end", default="E30F", help="End codepoint hex (default E30F)")
    parser.add_argument("--font", default="Bravura Text", help="Font name (default Bravura Text)")
    parser.add_argument(
        "--font_list",
        default="",
        help="Comma-separated font family names for side-by-side diagnostics",
    )
    parser.add_argument(
        "--try_common_sagittal_names",
        action="store_true",
        help="Use a built-in list of common Sagittal family names for diagnostics",
    )
    parser.add_argument("--size", type=int, default=3, help="LilyPond fontsize delta for glyph")
    parser.add_argument("--title", default="Sagittal Glyph Reference", help="Chart title")
    args = parser.parse_args()

    font_candidates: list[str] | None = None
    if args.try_common_sagittal_names:
        font_candidates = DEFAULT_FONT_CANDIDATES.copy()
    if args.font_list.strip():
        font_candidates = [x.strip() for x in args.font_list.split(",") if x.strip()]

    cp_start = parse_hex_codepoint(args.start)
    cp_end = parse_hex_codepoint(args.end)
    text = build_lilypond(
        cp_start,
        cp_end,
        args.font,
        args.size,
        args.title,
        font_candidates=font_candidates,
    )

    out_path = Path(args.output)
    out_path.write_text(text, encoding="utf-8")
    if font_candidates:
        print(
            f"Wrote {out_path} for U+{cp_start:04X}..U+{cp_end:04X} "
            f"with font candidates: {font_candidates}"
        )
    else:
        print(f"Wrote {out_path} for U+{cp_start:04X}..U+{cp_end:04X}")


if __name__ == "__main__":
    main()
