# Create a service and a pod that runs a jupyter notebook server accessing the TonicNet environment for slide_tuning. 
apiVersion: v1
kind: Service
metadata:
  name: tonicnet2-d
  labels:
    app: tonicnet2-d
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 8888
    nodePort: 30004
  selector:
    app: tonicnet2-d
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  labels:
    app: tonicnet2-d 
  name: tonicnet2-d
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: tonicnet2-d
  template: 
    metadata:
      labels:
        app: tonicnet2-d
    spec:
      nodeSelector:
        # kubernetes.io/hostname: fs6
        # intel.feature.node.kubernetes.io/gpu: "true"
      containers:
      - name: tonicnet
        image: quay.io/prentrodgers/python-music:0.4 
        imagePullPolicy: IfNotPresent
        workingDir: /home/prent
        command:  ["jupyter", "lab"] 
        args:
          - "--ip=0.0.0.0"
          - "--port=8888" 
          - "--no-browser"
          - "--allow-root"
          - "--NotebookApp.token=''"
          - "--ServerApp.allow_origin=*" 
        volumeMounts: 
        - mountPath: /home/prent
          name: ceph-files
        env: 
        - name: SFDIR
          value: "/home/prent/Music/sflib" 
        - name: SSDIR
          value: "/home/prent/Music/sflib" 
        - name: TZ
          value: "America/Los_Angeles"
        - name: HOME
          value: "/home/prent"
        - name: IMAGE_VERSION
          value: "/quay.io/prentrodgers/python-music:0.4"
        resources:
          requests:
            cpu: "0.5"
            memory: "8Gi"
          limits:
            cpu: "30"
            memory: "16Gi"
      volumes:
      - name: ceph-files
        persistentVolumeClaim:
            claimName: dropbox-pvc
            readOnly: false
      imagePullSecrets: 
        - name: regcred 