#!/usr/bin/env bash
# ray-grafana-dashboards.sh — load Ray's Grafana dashboards into Grafana.
#
#     ./ray-grafana-dashboards.sh          # needs a running `tuning` RayCluster
#
# Ray generates its dashboards (JSON) on the head at start-up, matching the
# metrics that Ray version emits.  This copies them out of the head and
# applies them as a ConfigMap in the prometheus namespace with the
# grafana_dashboard=1 label, which kube-prometheus-stack's Grafana sidecar
# watches — the same mechanism k8s-grafana-dashboards.yaml uses.  They show
# up in Grafana under the "Ray" folder within a minute.
#
# Nothing here is committed: the JSON is Ray's, not ours, and is regenerated
# whenever Ray is bumped (parallel-jobs/Containerfile RAY_VER) — re-run this
# after the first cluster on a new Ray version.  The scrape side is
# k8s-ray-monitoring.yaml.
#
# Only the two dashboards that mean anything here are loaded.  Ray also
# writes Serve, Train and LLM dashboards; with nothing emitting those
# metrics they would be empty.
set -euo pipefail
HEAD=$(kubectl get pod -l ray.io/cluster=tuning,ray.io/node-type=head -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
[ -n "$HEAD" ] || { echo "no tuning RayCluster is running (the dashboards are generated by the head)" >&2; exit 1; }
SRC=/tmp/ray/session_latest/metrics/grafana/dashboards
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT

# Ray titles them "Default Dashboard" and "Data Dashboard", which says
# nothing next to the other dashboards in Grafana: prefix the title and tag
# them, leaving the uid (rayDefaultDashboard) alone since the Ray dashboard's
# Metrics tab embeds panels by uid.
for f in default_grafana_dashboard.json data_grafana_dashboard.json; do
    kubectl exec "$HEAD" -c ray-head -- cat "$SRC/$f" \
      | python3 -c '
import json, sys
d = json.load(sys.stdin)
d["title"] = "Ray: " + d["title"].replace(" Dashboard", "").lower()
d["tags"] = sorted(set(d.get("tags", []) + ["ray", "one-footed-bride"]))
json.dump(d, sys.stdout, indent=1)
n, uid, title = len(d["panels"]), d["uid"], d["title"]
print(f"{sys.argv[1]:<32} {n} panels, uid {uid}, title {title!r}", file=sys.stderr)
' "$f" > "$TMP/ray-$f"
done

# Server-side apply: the two dashboards are ~400 KiB of JSON, more than the
# 256 KiB a client-side apply can stash in its last-applied annotation.
kubectl create configmap ray-dashboards -n prometheus \
    --from-file="$TMP" --dry-run=client -o yaml \
  | kubectl label --local -f - grafana_dashboard=1 app=ray-tuning -o yaml \
  | kubectl apply --server-side --force-conflicts -f -
echo "Grafana's sidecar loads them within ~60s: http://<any node>:30814, search \"Ray:\""
